local o = vim.opt
o.clipboard = "unnamedplus"
o.hlsearch = false
o.tabstop = 8
o.expandtab = true
o.shiftwidth = 4
o.softtabstop = 4
o.number = true
o.encoding = "utf-8"
o.backup = false
o.writebackup = false
o.cmdheight = 2
o.updatetime = 300
o.shortmess:append({c = true})
o.signcolumn = "number"
