format = "$username@$hostname$directory$git_branch$character"
add_newline = false

[username]
style_user = "blue bold"
style_root = "red bold"
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold dimmed gray"


[directory]
format = " [$path]($style)[$read_only]($read_only_style) "
style = "bold white"

[git_branch]
format = "\\[[$branch]($style)\\] "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
